
name: Build and Release frescopa

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name (optional)'
        required: false
        default: ''

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Install dependencies
        run: npm install

      - name: Zip site contents
        run: |
          cd site
          zip -r ../site.zip .
          cd ..

      - name: Get version from package.json
        id: get_version
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Create and push git tag
        run: |
          git config user.name "markszulc"
          git config user.email "mszulc@adobe.com"
          # Delete existing tag locally and remotely if it exists
          git tag -d v${{ steps.get_version.outputs.version }} || true
          git push origin :refs/tags/v${{ steps.get_version.outputs.version }} || true
          # Create and push new tag
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create frescopa zip
        run: |
          zip -r frescopa-${{ steps.get_version.outputs.version }}.zip site.zip previews package.json

      - name: Remove site.zip
        run: rm site.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: frescopa-${{ steps.get_version.outputs.version }}.zip
          name: ${{ github.event.inputs.release_name || format('frescopa-{0}', steps.get_version.outputs.version) }}
          tag_name: v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
